// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfflineBacklogManager.DBContexts;

namespace OfflineBacklogManager.Migrations
{
    [DbContext(typeof(OBMDBContext))]
    [Migration("20210417100214_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("OfflineBacklogManager.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("achievement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("achievement_max")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("appid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gamesystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ownership")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("playing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("progress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID")
                        .HasName("PK_UD");

                    b.ToTable("games");
                });
#pragma warning restore 612, 618
        }
    }
}
